// Danh sách các trường Đại học & Cao đẳng tại Việt Nam (dùng cho ô chọn trường học).
// Cho phép gõ để lọc và vẫn nhập tự do nếu trường không có trong danh sách.
export const schools = [
  // --- Đại học khu vực Hà Nội & phía Bắc ---
  'Đại học Quốc gia Hà Nội',
  'Trường Đại học Bách khoa Hà Nội',
  'Trường Đại học Kinh tế Quốc dân',
  'Trường Đại học Ngoại thương',
  'Trường Đại học Thương mại',
  'Học viện Tài chính',
  'Học viện Ngân hàng',
  'Trường Đại học Xây dựng Hà Nội',
  'Trường Đại học Giao thông Vận tải',
  'Trường Đại học Thủy lợi',
  'Trường Đại học Mỏ - Địa chất',
  'Trường Đại học Công nghiệp Hà Nội',
  'Trường Đại học Điện lực',
  'Trường Đại học Bách khoa - ĐHQGHN',
  'Trường Đại học Công nghệ - ĐHQGHN',
  'Trường Đại học Khoa học Tự nhiên - ĐHQGHN',
  'Trường Đại học Khoa học Xã hội và Nhân văn - ĐHQGHN',
  'Trường Đại học Kinh tế - ĐHQGHN',
  'Trường Đại học Ngoại ngữ - ĐHQGHN',
  'Trường Đại học Sư phạm Hà Nội',
  'Trường Đại học Sư phạm Hà Nội 2',
  'Trường Đại học Hà Nội',
  'Trường Đại học Luật Hà Nội',
  'Học viện Ngoại giao',
  'Học viện Báo chí và Tuyên truyền',
  'Học viện Bưu chính Viễn thông',
  'Học viện Nông nghiệp Việt Nam',
  'Học viện Kỹ thuật Quân sự',
  'Học viện Quân y',
  'Học viện Hành chính Quốc gia',
  'Trường Đại học Y Hà Nội',
  'Trường Đại học Dược Hà Nội',
  'Trường Đại học Y tế Công cộng',
  'Trường Đại học Kiến trúc Hà Nội',
  'Trường Đại học Mỹ thuật Công nghiệp',
  'Trường Đại học Văn hóa Hà Nội',
  'Trường Đại học Lao động - Xã hội',
  'Trường Đại học Công đoàn',
  'Trường Đại học Tài nguyên và Môi trường Hà Nội',
  'Trường Đại học Điện lực',
  'Trường Đại học Phenikaa',
  'Trường Đại học FPT',
  'Trường Đại học Đại Nam',
  'Trường Đại học Kinh doanh và Công nghệ Hà Nội',
  'Trường Đại học Thăng Long',
  'Trường Đại học Nguyễn Trãi',
  'Trường Đại học Hòa Bình',
  'Trường Đại học Thủ đô Hà Nội',
  'Trường Đại học Công nghệ Giao thông Vận tải',
  'Trường Đại học Công nghiệp Việt - Hung',
  'Trường Đại học Thái Nguyên',
  'Trường Đại học Kỹ thuật Công nghiệp Thái Nguyên',
  'Trường Đại học Nông Lâm Thái Nguyên',
  'Trường Đại học Y Dược Thái Nguyên',
  'Trường Đại học Hàng hải Việt Nam',
  'Trường Đại học Y Dược Hải Phòng',
  'Trường Đại học Hải Phòng',
  'Trường Đại học Hùng Vương (Phú Thọ)',
  'Trường Đại học Tân Trào',
  'Trường Đại học Tây Bắc',

  // --- Đại học khu vực Miền Trung ---
  'Đại học Đà Nẵng',
  'Trường Đại học Bách khoa - Đại học Đà Nẵng',
  'Trường Đại học Kinh tế - Đại học Đà Nẵng',
  'Trường Đại học Sư phạm - Đại học Đà Nẵng',
  'Trường Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng',
  'Trường Đại học Ngoại ngữ - Đại học Đà Nẵng',
  'Trường Đại học Duy Tân',
  'Trường Đại học Đông Á',
  'Đại học Huế',
  'Trường Đại học Khoa học - Đại học Huế',
  'Trường Đại học Y Dược - Đại học Huế',
  'Trường Đại học Kinh tế - Đại học Huế',
  'Trường Đại học Sư phạm - Đại học Huế',
  'Trường Đại học Nông Lâm - Đại học Huế',
  'Trường Đại học Vinh',
  'Trường Đại học Hồng Đức',
  'Trường Đại học Nha Trang',
  'Trường Đại học Quy Nhơn',
  'Trường Đại học Đà Lạt',
  'Trường Đại học Tây Nguyên',
  'Trường Đại học Quảng Nam',
  'Trường Đại học Phạm Văn Đồng',
  'Trường Đại học Quảng Bình',
  'Trường Đại học Hà Tĩnh',
  'Trường Đại học Phú Yên',
  'Trường Đại học Kiến trúc Đà Nẵng',

  // --- Đại học khu vực TP.HCM & phía Nam ---
  'Đại học Quốc gia TP.HCM',
  'Trường Đại học Bách khoa - ĐHQG TP.HCM',
  'Trường Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
  'Trường Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM',
  'Trường Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
  'Trường Đại học Kinh tế - Luật - ĐHQG TP.HCM',
  'Trường Đại học Quốc tế - ĐHQG TP.HCM',
  'Trường Đại học Kinh tế TP.HCM',
  'Trường Đại học Ngân hàng TP.HCM',
  'Trường Đại học Tài chính - Marketing',
  'Trường Đại học Ngoại thương (Cơ sở II - TP.HCM)',
  'Trường Đại học Sư phạm Kỹ thuật TP.HCM',
  'Trường Đại học Sư phạm TP.HCM',
  'Trường Đại học Công nghiệp TP.HCM',
  'Trường Đại học Công nghiệp Thực phẩm TP.HCM',
  'Trường Đại học Công Thương TP.HCM',
  'Trường Đại học Giao thông Vận tải TP.HCM',
  'Trường Đại học Kiến trúc TP.HCM',
  'Trường Đại học Y Dược TP.HCM',
  'Trường Đại học Y khoa Phạm Ngọc Thạch',
  'Trường Đại học Luật TP.HCM',
  'Trường Đại học Nông Lâm TP.HCM',
  'Trường Đại học Tôn Đức Thắng',
  'Trường Đại học Mở TP.HCM',
  'Trường Đại học Sài Gòn',
  'Trường Đại học Công nghệ TP.HCM (HUTECH)',
  'Trường Đại học Văn Lang',
  'Trường Đại học Hoa Sen',
  'Trường Đại học Nguyễn Tất Thành',
  'Trường Đại học Quốc tế Hồng Bàng',
  'Trường Đại học Văn Hiến',
  'Trường Đại học Gia Định',
  'Trường Đại học Kinh tế - Tài chính TP.HCM (UEF)',
  'Trường Đại học FPT (Cơ sở TP.HCM)',
  'Trường Đại học RMIT Việt Nam',
  'Trường Đại học Fulbright Việt Nam',
  'Trường Đại học Việt Đức',
  'Trường Đại học Tài nguyên và Môi trường TP.HCM',
  'Trường Đại học Thể dục Thể thao TP.HCM',
  'Trường Đại học Mỹ thuật TP.HCM',
  'Trường Đại học Sân khấu - Điện ảnh TP.HCM',
  'Trường Đại học Ngoại ngữ - Tin học TP.HCM (HUFLIT)',
  'Trường Đại học Sư phạm Thể dục Thể thao TP.HCM',
  'Trường Đại học Cần Thơ',
  'Trường Đại học Y Dược Cần Thơ',
  'Trường Đại học Kỹ thuật - Công nghệ Cần Thơ',
  'Trường Đại học Nam Cần Thơ',
  'Trường Đại học An Giang',
  'Trường Đại học Đồng Tháp',
  'Trường Đại học Tiền Giang',
  'Trường Đại học Trà Vinh',
  'Trường Đại học Bạc Liêu',
  'Trường Đại học Kiên Giang',
  'Trường Đại học Sư phạm Kỹ thuật Vĩnh Long',
  'Trường Đại học Cửu Long',
  'Trường Đại học Bà Rịa - Vũng Tàu',
  'Trường Đại học Thủ Dầu Một',
  'Trường Đại học Bình Dương',
  'Trường Đại học Quốc tế Miền Đông',
  'Trường Đại học Lạc Hồng',
  'Trường Đại học Đồng Nai',
  'Trường Đại học Công nghệ Đồng Nai',
  'Trường Đại học Nguyễn Huệ',
  'Trường Đại học Tây Đô',

  // --- Cao đẳng ---
  'Trường Cao đẳng Kỹ thuật Cao Thắng',
  'Trường Cao đẳng Công nghệ Thủ Đức',
  'Trường Cao đẳng Kinh tế Đối ngoại',
  'Trường Cao đẳng Công Thương TP.HCM',
  'Trường Cao đẳng Kỹ thuật Lý Tự Trọng TP.HCM',
  'Trường Cao đẳng FPT Polytechnic',
  'Trường Cao đẳng Công nghệ Bách khoa Hà Nội',
  'Trường Cao đẳng Công nghiệp Hà Nội',
  'Trường Cao đẳng Xây dựng Công trình Đô thị',
  'Trường Cao đẳng Du lịch Hà Nội',
  'Trường Cao đẳng Cơ điện Hà Nội',
  'Trường Cao đẳng Nghề Công nghiệp Hà Nội',
  'Trường Cao đẳng Điện tử - Điện lạnh Hà Nội',
  'Trường Cao đẳng Y tế Hà Nội',
  'Trường Cao đẳng Kinh tế Kỹ thuật TP.HCM',
  'Trường Cao đẳng Kỹ nghệ II',
  'Trường Cao đẳng Giao thông Vận tải TP.HCM',
  'Trường Cao đẳng Kỹ thuật Công nghệ Bà Rịa - Vũng Tàu',
  'Trường Cao đẳng Công nghệ và Thương mại Hà Nội',
  'Trường Cao đẳng Y Dược Sài Gòn',
  'Trường Cao đẳng Y tế Đồng Nai',
  'Trường Cao đẳng Công nghiệp Bắc Ninh',
  'Trường Cao đẳng Công nghiệp Thái Nguyên',
  'Trường Cao đẳng Nghề Đà Nẵng',
  'Trường Cao đẳng Công nghệ - Kinh tế và Thủy lợi Miền Trung',
  'Trường Cao đẳng Cần Thơ',
  'Trường Cao đẳng Kinh tế - Kỹ thuật Cần Thơ',

  // --- Khác ---
  'Trường khác (nhập tay)',
];
